### ISSUE TITLE
no citation option on chat texts

### ISSUE THREAD

**Issue by wumpalumpa** [OfficeDev/msteams-app-lms-meetings#4]
I haven't seen the citation option on the chats and/or other sections of MS Teams app

is that normal?

skype has it // is a quite common action in most apps, and it is quite useful also

**Comment by aosolis** [comment]
Hi @wumpalumpa! This issues section is for this sample app only.
For Teams feature requests, please go to [User Voice](https://microsoftteams.uservoice.com/). There's already a few requests for this, and I recommend that you add your vote to an existing suggestion, perhaps this one: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/40226587-quote-a-message-and-reply-option
